import { useQuery } from '@tanstack/react-query'
import { Link, useSearchParams } from 'react-router-dom'
import { Search } from 'lucide-react'
import { api } from '../../lib/api'
import { publicKey } from '../../lib/query-client'
import { formatVnd } from '../../lib/money'
import { PageState } from '../../components/PageState'
import { imageUrl, type Category, type Page, type ProductSummary } from './types'
export function ProductCard({ product }: { product: ProductSummary }) {
  const photo = imageUrl(product.images[0])
  return <article className="product-card"><Link className="product-image" to={`/products/${encodeURIComponent(product.slug)}`}>{photo ? <img src={photo} alt={`${product.name}${product.images[0].illustrative ? ' — illustrative image' : ''}`} loading="lazy" /> : <div className="image-placeholder" aria-label="No product image available" />}{product.images[0]?.illustrative && <span className="product-badge">Illustrative image</span>}</Link><div className="product-body"><span className="product-category">{product.category.name}</span><Link className="product-name" to={`/products/${encodeURIComponent(product.slug)}`}>{product.name}</Link><div className="product-bottom"><span className="product-price">{product.startingPriceVnd === null ? 'Price pending' : `From ${formatVnd(product.startingPriceVnd)}`}</span><span className="availability">{product.purchasable ? 'Available to order' : 'Unavailable to order'}</span></div></div></article>
}
export function ProductListPage() {
  const [params, setParams] = useSearchParams()
  const q = params.get('q') ?? '', category = params.get('category') ?? '', sort = params.get('sort') ?? 'newest'
  const page = Math.max(1, Number(params.get('page')) || 1)
  const validSort = ['newest', 'name', 'price_asc', 'price_desc'].includes(sort) ? sort : 'newest'
  const query = useQuery({ queryKey: publicKey('products', q, category, validSort, page), queryFn: ({ signal }) => api<Page<ProductSummary>>(`/products?${new URLSearchParams({ ...(q ? { q } : {}), ...(category ? { category } : {}), sort: validSort, page: String(page) })}`, { signal }) })
  const categories = useQuery({ queryKey: publicKey('categories'), queryFn: ({ signal }) => api<Page<Category>>('/categories?pageSize=100', { signal }) })
  function change(key: string, value: string) { setParams(current => { const next = new URLSearchParams(current); if (value) next.set(key, value); else next.delete(key); if (key !== 'page') next.delete('page'); return next }) }
  return <section className="section products-section container"><div className="section-heading products-heading"><div><span className="section-kicker">PRODUCT CATALOG</span><h1>Products</h1><p>Explore confirmed listings. Availability and prices may change.</p></div>{query.data && <span className="result-count">{query.data.total} products</span>}</div><div className="catalog-toolbar"><div className="filter-list"><button className={`filter-chip ${!category ? 'active' : ''}`} onClick={() => change('category', '')}>All</button>{categories.data?.items.map(item => <button key={item.id} className={`filter-chip ${category === item.slug ? 'active' : ''}`} onClick={() => change('category', item.slug)}>{item.name}</button>)}</div><label className="search-box"><Search size={18} /><input type="search" value={q} onChange={event => change('q', event.target.value)} placeholder="Search products..." aria-label="Search products" /></label><label className="sort-box">Sort <select value={validSort} onChange={event => change('sort', event.target.value)}><option value="newest">Newest</option><option value="name">Name</option><option value="price_asc">Price: low to high</option><option value="price_desc">Price: high to low</option></select></label></div>{query.isPending ? <PageState title="Loading products" /> : query.isError ? <PageState title="Products are unavailable">Please try again later.</PageState> : query.data.items.length ? <><div className="product-grid">{query.data.items.map(product => <ProductCard product={product} key={product.id} />)}</div><div className="pagination"><button disabled={page <= 1} onClick={() => change('page', String(page - 1))}>Previous</button><span>Page {page}</span><button disabled={page * query.data.pageSize >= query.data.total} onClick={() => change('page', String(page + 1))}>Next</button></div></> : <PageState title="No products found">Try another search term or browse the full catalog.</PageState>}<p className="catalog-note">Images labeled illustrative are visual references. Product details come from AnhEmFarm listings.</p></section>
}
