import { expect, test } from '@playwright/test'
import { execFileSync, spawn, type ChildProcess } from 'node:child_process'
import { once } from 'node:events'
import type { Scenario } from '../server/test/fixtures'

test('real seller fulfillment updates customer order and collected dashboard value', async ({ page }) => {
  test.setTimeout(120000)
  execFileSync(process.execPath, ['node_modules/typescript/bin/tsc', '-p', 'tsconfig.json'], { cwd: 'server', stdio: 'pipe' })
  const backend: ChildProcess = spawn(process.execPath, ['dist/test/browser-server.js'], { cwd: 'server', stdio: ['ignore', 'ignore', 'ignore', 'ipc'] })
  try {
    const [ready] = await Promise.race([once(backend, 'message'), once(backend, 'exit').then(() => { throw new Error('Local test backend failed to start') })])
    const fixture = ready.fixture as Scenario
    const orderReady = once(backend, 'message'); backend.send!({ action: 'order' })
    const [created] = await orderReady
    if (created.done !== 'order' || !created.orderId) throw new Error('Local order fixture failed')
    await page.goto('/login')
    await page.getByLabel('Email').fill(fixture.admin.email)
    await page.getByLabel('Password', { exact: true }).fill(fixture.admin.password)
    await page.getByRole('button', { name: 'Sign in', exact: true }).click()
    await expect(page.getByRole('link', { name: 'Test Admin', exact: true })).toBeVisible()
    await page.goto('/admin')
    await expect(page.getByRole('heading', { name: 'Seller dashboard' })).toBeVisible()
    await page.goto('/admin/orders')
    const reference = created.orderId.slice(0, 8).toUpperCase()
    const vietnamDate = new Date(Date.now() + 7 * 60 * 60 * 1000).toISOString().slice(0, 10)
    await page.getByLabel('Search orders').fill(reference)
    await page.getByLabel('Status').selectOption('PENDING')
    await page.getByLabel('From (Vietnam date)').fill(vietnamDate)
    await page.getByLabel('To (Vietnam date)').fill(vietnamDate)
    await page.getByRole('button', { name: 'Apply filters' }).click()
    const filteredOrder = page.locator('tr').filter({
      has: page.getByRole('link', { name: reference, exact: true })
    })
    await expect(filteredOrder.getByText('PENDING', { exact: true })).toBeVisible()
    const reportsUrl = `/admin/reports?from=${vietnamDate}&to=${vietnamDate}`
    await page.goto(reportsUrl)
    const collectedValue = page.locator('.metrics div').filter({ hasText: 'COD collected' }).locator('strong')
    const dueValue = page.locator('.metrics div').filter({ hasText: 'COD due' }).locator('strong')
    const amount = (text: string) => Number(text.replace(/[^0-9]/g, ''))
    const before = amount(await collectedValue.innerText())
    const dueBefore = amount(await dueValue.innerText())
    await page.goto(`/admin/orders/${created.orderId}`)
    await page.screenshot({ path: test.info().outputPath('admin-order-detail.png'), fullPage: true })
    await page.getByRole('button', { name: 'Confirm order' }).click()
    await expect(page.getByRole('button', { name: 'Start store delivery' })).toBeVisible()
    await page.getByRole('button', { name: 'Start store delivery' }).click()
    await expect(page.getByRole('button', { name: 'Mark delivered' })).toBeVisible()
    await page.getByRole('button', { name: 'Mark delivered' }).click()
    await expect(page.getByRole('button', { name: 'Mark COD collected' })).toBeVisible()
    await page.getByRole('button', { name: 'Mark COD collected' }).click()
    await expect(page.getByRole('button', { name: 'Correct COD to due' })).toBeVisible()
    await page.goto(reportsUrl)
    await expect(collectedValue).toBeVisible()
    expect(amount(await collectedValue.innerText())).toBe(before + fixture.variant.priceVnd + 30000)
    const deliveredValue = page.locator('.metrics div').filter({ hasText: 'Delivered order value' }).locator('strong')
    const deliveredAfterFirst = amount(await deliveredValue.innerText())
    await page.goto(`/admin/orders/${created.orderId}`)
    await page.getByRole('textbox', { name: /reason/i }).fill('Collection recorded by mistake')
    await page.getByRole('button', { name: 'Correct COD to due' }).click()
    await expect(page.getByRole('button', { name: 'Mark COD collected' })).toBeVisible()
    await page.goto(reportsUrl)
    expect(amount(await collectedValue.innerText())).toBe(before)
    expect(amount(await dueValue.innerText())).toBe(dueBefore + fixture.variant.priceVnd + 30000)
    const nextOrder = async () => { const response = once(backend, 'message'); backend.send!({ action: 'order' }); const [message] = await response
      if (message.done !== 'order' || !message.orderId) throw new Error('Local order fixture failed'); return message.orderId as string }
    const cancelledId = await nextOrder()
    await page.goto(`/admin/orders/${cancelledId}`)
    await page.getByRole('textbox', { name: /reason/i }).fill('Customer requested cancellation')
    await page.getByRole('button', { name: 'Cancel order' }).click()
    await expect(page.getByText(/CANCELLED · COD/)).toBeVisible()
    const returnedId = await nextOrder()
    await page.goto(`/admin/orders/${returnedId}`)
    await page.getByRole('button', { name: 'Confirm order' }).click()
    await page.getByRole('button', { name: 'Start store delivery' }).click()
    await page.getByRole('textbox', { name: /reason/i }).fill('Damaged in delivery')
    await page.getByRole('checkbox', { name: 'Returned items physically received' }).check()
    await page.getByRole('button', { name: 'Record return' }).click()
    await expect(page.getByText(/RETURNED · COD/)).toBeVisible()
    await page.goto(reportsUrl)
    expect(amount(await deliveredValue.innerText())).toBe(deliveredAfterFirst)
    await page.getByRole('button', { name: 'Log out' }).first().click()
    await page.goto('/login')
    await page.getByLabel('Email').fill(fixture.customer.email)
    await page.getByLabel('Password', { exact: true }).fill(fixture.customer.password)
    await page.getByRole('button', { name: 'Sign in', exact: true }).click()
    await expect(page.getByRole('link', { name: 'Test Customer', exact: true })).toBeVisible()
    await page.goto(`/account/orders/${created.orderId}`)
    await expect(page.getByText('Delivered', { exact: true })).toBeVisible()
  } finally {
    if (backend.exitCode === null && backend.signalCode === null) { const exited = once(backend, 'exit'); backend.kill('SIGTERM'); await exited }
  }
})
