import { useState } from 'react'
import { Link, NavLink, Outlet } from 'react-router-dom'
import { Menu, Search, X } from 'lucide-react'
import { Dialog } from './Dialog'
import { useSession } from '../features/auth/session'
function Brand() { return <Link className="brand" to="/" aria-label="AnhEmFarm home"><span className="brand-mark" aria-hidden="true"><span className="berry berry-one" /><span className="berry berry-two" /><span className="berry berry-three" /><span className="berry-leaf" /></span><span>AnhEm<span>Farm</span></span></Link> }
export function Layout() {
  const [menu, setMenu] = useState(false)
  const [logoutError, setLogoutError] = useState('')
  const { user, logout } = useSession()
  const signOut = () => { setLogoutError(''); void logout().catch(() => setLogoutError('Could not sign out. Please try again.')) }
  return <div className="site-shell"><div className="announcement">Welcome to AnhEmFarm — good food for every day</div><header className="site-header"><div className="container header-inner"><Brand /><nav className="desktop-nav" aria-label="Main navigation"><NavLink to="/">Home</NavLink><NavLink to="/products">Products</NavLink><Link to="/products?category=mulberries">Mulberries</Link><Link to="/products?category=coffee">Coffee</Link></nav><div className="header-actions"><Link className="account-link" to="/cart">Cart</Link><Link className="icon-button" to="/products" aria-label="Search products"><Search size={21} /></Link>{user ? <><Link className="account-name" to="/account">{user.name}</Link>{user.role === 'ADMIN' && <Link className="account-link" to="/admin/products">Admin</Link>}<button className="account-link" onClick={signOut}>Log out</button></> : <Link className="account-link" to="/login">Sign in</Link>}<button className="icon-button mobile-menu-button" aria-label="Open menu" onClick={() => setMenu(true)}><Menu size={22} /></button></div></div></header><main>{logoutError && <p className="container error-message" role="alert">{logoutError}</p>}<Outlet /></main><footer className="footer"><div className="container footer-main"><div><Brand /><p>A small home for everyday farm flavors.</p></div><div className="footer-links"><div><strong>Explore</strong><Link to="/">Home</Link><Link to="/products">Products</Link></div><div><strong>Account</strong>{user ? <button onClick={signOut}>Log out</button> : <Link to="/login">Sign in</Link>}<Link to="/register">Create account</Link></div></div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} AnhEmFarm</span><span>Product details are being updated.</span></div></footer>{menu && <Dialog title="Menu" onClose={() => setMenu(false)}><nav className="mobile-links"><Link onClick={() => setMenu(false)} to="/cart">Cart</Link>{user && <Link onClick={() => setMenu(false)} to="/account">My account</Link>}<Link onClick={() => setMenu(false)} to="/">Home</Link><Link onClick={() => setMenu(false)} to="/products">Products</Link><Link onClick={() => setMenu(false)} to="/products?category=mulberries">Mulberries</Link><Link onClick={() => setMenu(false)} to="/products?category=coffee">Coffee</Link></nav><button className="menu-close" onClick={() => setMenu(false)}><X size={16} /> Close</button></Dialog>}</div>
}
